---
title: "Transformação e Remodelagem de dados"
author: "Wellington Santos"
date: "09/03/2022"
output: html_document
---

## Manipulando data frames com o R Base

Limpando Ambiente Global
```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = "")
rm(list=ls(all=T))
```

Banco de dados
```{r}
## banco de dados do R base
iris1 <- iris

## visualizando banco de dados
View(iris1)

## tipo de dados
str(iris1)

## resumo de estatísticas básica dos dados
summary(iris1)
```

Acessando elementos do data frame
```{r}
## elemento da primeira linha segunda coluna
iris1[1,2]

## primeira linha todas as colunas
iris1[1,]

## terceira coluna
iris1[,3]

## coluna Petal.Length
iris1$Petal.Length
iris1[,"Petal.Length"]
```

Operações matemáticas nas colunas
```{r}
## média Sepal.Width
mean(iris1$Sepal.Width)

## soma Sepal.Width
sum(iris1$Sepal.Width)

## desvio padrão
sd(iris1$Sepal.Width)
```
Aplicando alguns filtros
```{r}
## especie versicolor
versicolor <- iris1[iris1$Species == "versicolor",]

## Petal.Length menor que 2
menor2 <- iris1[iris1$Petal.Length < 2,]

## Petal.Length maior que 2 e menor que 4
maior2menor4 <- iris1[iris1$Petal.Length > 2 & iris1$Petal.Length < 4,]

## excluindo coluna Petal.Length 
irisSemPetal.Length <- iris1[,-3]
```





















